-- MySQL Script generated by MySQL Workbench
-- Fri Sep 29 22:43:27 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema moviealert
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema moviealert
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `moviealert` DEFAULT CHARACTER SET utf8 ;
USE `moviealert` ;

-- -----------------------------------------------------
-- Table `moviealert`.`filme`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moviealert`.`filme` (
  `idfilme` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(100) NOT NULL,
  `descricao` TEXT NULL,
  `duracao` TIME NULL,
  `data_lancamento` DATE NULL,
  PRIMARY KEY (`idfilme`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `moviealert`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moviealert`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(100) NOT NULL,
  `email` VARCHAR(105) NULL,
  `senha` VARCHAR(75) NOT NULL,
  PRIMARY KEY (`idusuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `moviealert`.`favorito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moviealert`.`favorito` (
  `idfavorito` INT NOT NULL,
  `idfilme` INT NOT NULL AUTO_INCREMENT,
  `idusuario` INT NOT NULL,
  PRIMARY KEY (`idfavorito`),
  INDEX `fk_filme_has_login_login1_idx` (`idusuario` ASC),
  INDEX `fk_filme_has_login_filme_idx` (`idfilme` ASC),
  CONSTRAINT `fk_filme_has_login_filme`
    FOREIGN KEY (`idfilme`)
    REFERENCES `moviealert`.`filme` (`idfilme`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_filme_has_login_login1`
    FOREIGN KEY (`idusuario`)
    REFERENCES `moviealert`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
